In [2]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array=np.array([23,81,99,66,13])
print(array)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))

[23 81 99 66 13]
[13 23 66 81 99]


In [7]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a1 = np.array([10, 15, 30, 45, 60])
print(a1)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a2= np.arange(5, 15)
print(a2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a3 = np.arange(50, 100, 5)
print(a3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a4 = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
a5=np.ones(10)
print(a5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arr = np.linspace(0, 100, 5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_integers = np.random.randint(10, 31, 5)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

random_numbers = np.random.uniform(-1, 1, 10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_matrix = np.random.randint(10, 51, size=(3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_sums = np.sum(random_matrix, axis=1)
column_sums = np.sum(random_matrix, axis=0)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = np.max(random_matrix)
min_value = np.min(random_matrix)
mean_value = np.mean(random_matrix)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.argmax(random_matrix)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arr = np.arange(10, 21)
first_three_elements = arr[:3]

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
reversed_arr = np.flip(arr)

# 15- Üretilen matrisin ilk satırını seçiniz.
first_row = random_matrix[0]

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
element_2_3 = random_matrix[1, 2]

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
first_elements = random_matrix[:, 0]

# 18- Üretilen matrisin her bir elemanının karesini alınız.
squared_matrix = np.square(random_matrix)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
positive_even_numbers = random_matrix[(random_matrix % 2 == 0) & (random_matrix > 0)]

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
