In [2]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array=np.array([23,81,99,66,13])
print(array)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))

[23 81 99 66 13]
[13 23 66 81 99]


In [29]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a1 = np.array([10, 15, 30, 45, 60])
print(a1)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a2= np.arange(5, 15)
print(a2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a3 = np.arange(50, 100, 5)
print(a3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a4 = np.zeros(10)
print(a4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
a5=np.ones(10)
print(a5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
a6 = np.linspace(0, 100, 5)
print(a6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_numbers = np.random.randint(10, 31, 5)
print(random_numbers)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.

random_numbers2 = np.random.uniform(-1, 1, 10)
print(random_numbers2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3 = np.random.randint(10, 50, size=(3, 5))
print(random_numbers3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers3.sum(axis=0))
print(random_numbers3.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random_numbers3.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random_numbers4=np.random.randint(10,20,8)
print(random_numbers4[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print( random_numbers3[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print( random_numbers3[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print( random_numbers3**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5=np.random.randint(-50,50,size=(3,5))
print( (random_numbers5>0 ) & (random_numbers5 % 2==0))




[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[21 16 27 28 15]
[-0.41097472  0.21277547 -0.29719844  0.93520119 -0.0971711   0.19600624
 -0.46261112 -0.12958244 -0.645713   -0.79309822]
[[20 48 16 15 17]
 [19 26 15 22 43]
 [26 20 40 25 35]]
[65 94 71 62 95]
[116 125 146]
48
15
25.8
1
[14 13 13]
[13 16 12 16 13 13 13 14]
[20 48 16 15 17]
15
[20 19 26]
[[ 400 2304  256  225  289]
 [ 361  676  225  484 1849]
 [ 676  400 1600  625 1225]]
[[False  True False False False]
 [False False False False False]
 [False False False False False]]
