# Problem 1

In [8]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 10, size=(5))

# 3 - matris'in boyutunu öğrenin
print("Matris boyutu:", matris.shape)

# 4 - matris'i yeniden boyutlandırın
matris = matris.reshape((1,5))

# 5 - matris'in boyut sayısını öğrenin
print("Matris boyut sayısı:", matris.ndim)


Matris boyutu: (5,)
Matris boyut sayısı: 2


# Problem 2

In [14]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 10, 2)
print("Oluşturulan Matris:", matris)

# 2 - Oluşturduğunuz matrisi parçalayın
matris1, matris2 = np.array_split(matris, 2)
print("Parçalanan Matrisler:\n",matris1,"\n", matris2)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis_matris = np.concatenate((matris1, matris2))
print("Birleştirilen Matris:", birlesmis_matris)


Oluşturulan Matris: [1 3 5 7 9]
Parçalanan Matrisler:
 [1 3 5] 
 [7 9]
Birleştirilen Matris: [1 3 5 7 9]


# Problem 3

In [38]:
import numpy as np

# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.choice(np.arange(5, 101, 2), size=(2,5), replace=False)
print("Matris:\n",matris)

# 2 - matris'in özelliklerini inceleyin
print("Matrisin satır sayısı:", matris.shape[0],",Sütun sayısı:",matris.shape[1] )
print("Matrisin boyut sayısı:", matris.ndim)
print("Matrisin eleman sayısı:", matris.size)
print("Matris elemanlarının toplamı:", np.sum(matris))
print("Matris elemanlarının en küçüğü:", np.max(matris))
print("Matris elemanlarının en büyüğü:", np.min(matris))
print("Matris elemanlarının ortalaması:", np.mean(matris))
print("Matris elemanlarının ortancası:", np.median(matris))
print("Matris elemanlarının standart sapması:", np.std(matris))


Matris:
 [[89 51  9 95 35]
 [85 57 39 55 33]]
Matrisin satır sayısı: 2 ,Sütun sayısı: 5
Matrisin boyut sayısı: 2
Matrisin eleman sayısı: 10
Matris elemanlarının toplamı: 548
Matris elemanlarının en küçüğü: 95
Matris elemanlarının en büyüğü: 9
Matris elemanlarının ortalaması: 54.8
Matris elemanlarının ortancası: 53.0
Matris elemanlarının standart sapması: 26.327931935493908
